apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmo-client
  namespace: bot-bmo-alpha
spec:
  selector:
    matchLabels:
      app: bmo-client
  replicas: 3
  template:
    metadata:
      labels:
        app: bmo-client
    spec:
      containers:
        - name: bmo-client-container
          image: eu.gcr.io/bot-bmo-290008/bmo-client-app:latest
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          imagePullPolicy: Always
