// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: bmo_service.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term       string `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Definition string `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	Weight     int32  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmo_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_bmo_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_bmo_service_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *Card) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *Card) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type CardSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	NumCards    int32                `protobuf:"varint,3,opt,name=num_cards,json=numCards,proto3" json:"num_cards,omitempty"`
	Cards       []*Card              `protobuf:"bytes,4,rep,name=cards,proto3" json:"cards,omitempty"`
	LastoOpened *timestamp.Timestamp `protobuf:"bytes,5,opt,name=lastoOpened,proto3" json:"lastoOpened,omitempty"`
}

func (x *CardSet) Reset() {
	*x = CardSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmo_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardSet) ProtoMessage() {}

func (x *CardSet) ProtoReflect() protoreflect.Message {
	mi := &file_bmo_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardSet.ProtoReflect.Descriptor instead.
func (*CardSet) Descriptor() ([]byte, []int) {
	return file_bmo_service_proto_rawDescGZIP(), []int{1}
}

func (x *CardSet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CardSet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CardSet) GetNumCards() int32 {
	if x != nil {
		return x.NumCards
	}
	return 0
}

func (x *CardSet) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *CardSet) GetLastoOpened() *timestamp.Timestamp {
	if x != nil {
		return x.LastoOpened
	}
	return nil
}

type InsertCardSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardSet *CardSet `protobuf:"bytes,2,opt,name=card_set,json=cardSet,proto3" json:"card_set,omitempty"`
}

func (x *InsertCardSetRequest) Reset() {
	*x = InsertCardSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmo_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertCardSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertCardSetRequest) ProtoMessage() {}

func (x *InsertCardSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bmo_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertCardSetRequest.ProtoReflect.Descriptor instead.
func (*InsertCardSetRequest) Descriptor() ([]byte, []int) {
	return file_bmo_service_proto_rawDescGZIP(), []int{2}
}

func (x *InsertCardSetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InsertCardSetRequest) GetCardSet() *CardSet {
	if x != nil {
		return x.CardSet
	}
	return nil
}

type InsertCardSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *InsertCardSetResponse) Reset() {
	*x = InsertCardSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmo_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertCardSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertCardSetResponse) ProtoMessage() {}

func (x *InsertCardSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bmo_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertCardSetResponse.ProtoReflect.Descriptor instead.
func (*InsertCardSetResponse) Descriptor() ([]byte, []int) {
	return file_bmo_service_proto_rawDescGZIP(), []int{3}
}

func (x *InsertCardSetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FetchCardSetByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FetchCardSetByIDRequest) Reset() {
	*x = FetchCardSetByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmo_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchCardSetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCardSetByIDRequest) ProtoMessage() {}

func (x *FetchCardSetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bmo_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCardSetByIDRequest.ProtoReflect.Descriptor instead.
func (*FetchCardSetByIDRequest) Descriptor() ([]byte, []int) {
	return file_bmo_service_proto_rawDescGZIP(), []int{4}
}

func (x *FetchCardSetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FetchCardSetByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardSet *CardSet `protobuf:"bytes,1,opt,name=card_set,json=cardSet,proto3" json:"card_set,omitempty"`
}

func (x *FetchCardSetByIDResponse) Reset() {
	*x = FetchCardSetByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bmo_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchCardSetByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchCardSetByIDResponse) ProtoMessage() {}

func (x *FetchCardSetByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bmo_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchCardSetByIDResponse.ProtoReflect.Descriptor instead.
func (*FetchCardSetByIDResponse) Descriptor() ([]byte, []int) {
	return file_bmo_service_proto_rawDescGZIP(), []int{5}
}

func (x *FetchCardSetByIDResponse) GetCardSet() *CardSet {
	if x != nil {
		return x.CardSet
	}
	return nil
}

var File_bmo_service_proto protoreflect.FileDescriptor

var file_bmo_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x6d, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x72, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0xaa, 0x01, 0x0a,
	0x07, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x05, 0x63,
	0x61, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x12, 0x3c, 0x0a, 0x0b, 0x6c,
	0x61, 0x73, 0x74, 0x6f, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61,
	0x73, 0x74, 0x6f, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x22, 0x57, 0x0a, 0x14, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x08, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x52, 0x07, 0x63, 0x61, 0x72, 0x64, 0x53,
	0x65, 0x74, 0x22, 0x27, 0x0a, 0x15, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x61, 0x72, 0x64,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x17, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x18, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43,
	0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x26, 0x0a, 0x08, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x73, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65,
	0x74, 0x52, 0x07, 0x63, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x32, 0xa1, 0x01, 0x0a, 0x0a, 0x42,
	0x4d, 0x4f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74,
	0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4d, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x74, 0x42,
	0x79, 0x49, 0x44, 0x12, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x61,
	0x72, 0x64, 0x53, 0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x43, 0x61, 0x72, 0x64, 0x53,
	0x65, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bmo_service_proto_rawDescOnce sync.Once
	file_bmo_service_proto_rawDescData = file_bmo_service_proto_rawDesc
)

func file_bmo_service_proto_rawDescGZIP() []byte {
	file_bmo_service_proto_rawDescOnce.Do(func() {
		file_bmo_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bmo_service_proto_rawDescData)
	})
	return file_bmo_service_proto_rawDescData
}

var file_bmo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bmo_service_proto_goTypes = []interface{}{
	(*Card)(nil),                     // 0: v1.Card
	(*CardSet)(nil),                  // 1: v1.CardSet
	(*InsertCardSetRequest)(nil),     // 2: v1.InsertCardSetRequest
	(*InsertCardSetResponse)(nil),    // 3: v1.InsertCardSetResponse
	(*FetchCardSetByIDRequest)(nil),  // 4: v1.FetchCardSetByIDRequest
	(*FetchCardSetByIDResponse)(nil), // 5: v1.FetchCardSetByIDResponse
	(*timestamp.Timestamp)(nil),      // 6: google.protobuf.Timestamp
}
var file_bmo_service_proto_depIdxs = []int32{
	0, // 0: v1.CardSet.cards:type_name -> v1.Card
	6, // 1: v1.CardSet.lastoOpened:type_name -> google.protobuf.Timestamp
	1, // 2: v1.InsertCardSetRequest.card_set:type_name -> v1.CardSet
	1, // 3: v1.FetchCardSetByIDResponse.card_set:type_name -> v1.CardSet
	2, // 4: v1.BMOService.InsertCardSet:input_type -> v1.InsertCardSetRequest
	4, // 5: v1.BMOService.FetchCardSetByID:input_type -> v1.FetchCardSetByIDRequest
	3, // 6: v1.BMOService.InsertCardSet:output_type -> v1.InsertCardSetResponse
	5, // 7: v1.BMOService.FetchCardSetByID:output_type -> v1.FetchCardSetByIDResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bmo_service_proto_init() }
func file_bmo_service_proto_init() {
	if File_bmo_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bmo_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmo_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CardSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmo_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertCardSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmo_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertCardSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmo_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchCardSetByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bmo_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchCardSetByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bmo_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bmo_service_proto_goTypes,
		DependencyIndexes: file_bmo_service_proto_depIdxs,
		MessageInfos:      file_bmo_service_proto_msgTypes,
	}.Build()
	File_bmo_service_proto = out.File
	file_bmo_service_proto_rawDesc = nil
	file_bmo_service_proto_goTypes = nil
	file_bmo_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BMOServiceClient is the client API for BMOService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BMOServiceClient interface {
	InsertCardSet(ctx context.Context, in *InsertCardSetRequest, opts ...grpc.CallOption) (*InsertCardSetResponse, error)
	FetchCardSetByID(ctx context.Context, in *FetchCardSetByIDRequest, opts ...grpc.CallOption) (*FetchCardSetByIDResponse, error)
}

type bMOServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBMOServiceClient(cc grpc.ClientConnInterface) BMOServiceClient {
	return &bMOServiceClient{cc}
}

func (c *bMOServiceClient) InsertCardSet(ctx context.Context, in *InsertCardSetRequest, opts ...grpc.CallOption) (*InsertCardSetResponse, error) {
	out := new(InsertCardSetResponse)
	err := c.cc.Invoke(ctx, "/v1.BMOService/InsertCardSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bMOServiceClient) FetchCardSetByID(ctx context.Context, in *FetchCardSetByIDRequest, opts ...grpc.CallOption) (*FetchCardSetByIDResponse, error) {
	out := new(FetchCardSetByIDResponse)
	err := c.cc.Invoke(ctx, "/v1.BMOService/FetchCardSetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BMOServiceServer is the server API for BMOService service.
type BMOServiceServer interface {
	InsertCardSet(context.Context, *InsertCardSetRequest) (*InsertCardSetResponse, error)
	FetchCardSetByID(context.Context, *FetchCardSetByIDRequest) (*FetchCardSetByIDResponse, error)
}

// UnimplementedBMOServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBMOServiceServer struct {
}

func (*UnimplementedBMOServiceServer) InsertCardSet(context.Context, *InsertCardSetRequest) (*InsertCardSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertCardSet not implemented")
}
func (*UnimplementedBMOServiceServer) FetchCardSetByID(context.Context, *FetchCardSetByIDRequest) (*FetchCardSetByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchCardSetByID not implemented")
}

func RegisterBMOServiceServer(s *grpc.Server, srv BMOServiceServer) {
	s.RegisterService(&_BMOService_serviceDesc, srv)
}

func _BMOService_InsertCardSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertCardSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BMOServiceServer).InsertCardSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.BMOService/InsertCardSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BMOServiceServer).InsertCardSet(ctx, req.(*InsertCardSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BMOService_FetchCardSetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchCardSetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BMOServiceServer).FetchCardSetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.BMOService/FetchCardSetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BMOServiceServer).FetchCardSetByID(ctx, req.(*FetchCardSetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BMOService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.BMOService",
	HandlerType: (*BMOServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertCardSet",
			Handler:    _BMOService_InsertCardSet_Handler,
		},
		{
			MethodName: "FetchCardSetByID",
			Handler:    _BMOService_FetchCardSetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bmo_service.proto",
}
